version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: deps(gh-actions)
    labels: [dependencies]

  - package-ecosystem: gradle
    directory: /
    open-pull-requests-limit: 25
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: deps(java)
    labels: [dependencies]
