
dependencies {
  api libs.slf4j.api

  api libs.progresso.core
  api libs.progresso.log4j2
  api libs.progresso.consolewidth.unixish

  api libs.log4j.core
  api libs.log4j.slf4j2

  testImplementation project(":testing")
  testImplementation libs.randomizedtesting.runner
  testImplementation libs.assertj

  annotationProcessor libs.log4j.core
}

javadoc {
  exclude 'com/carrotsearch/console/jcommander/**'
}

jar {
  def runtimeClasspath = configurations.runtimeClasspath
  def moduleName = project.group + "." + project.name

  // The manifest's Class-Path is computed in doFirst, declare what it depends on.
  inputs.files(runtimeClasspath)

  doFirst {
    manifest {
      attributes(["Main-Class": "com.carrotsearch.console.launcher.Launcher",
        "Class-Path": runtimeClasspath.collect {
          it.getName()
        }.join(' '),
        "Automatic-Module-Name": moduleName])
    }
  }
}
